### ISSUE TITLE
Prepare to upgrade to graphene-tornado 2.6

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-uiserver#102]
**Describe exactly what you would like to see in an upcoming release**

We should prepare to upgrade our version of `graphene-tornado`. We are still using 2.1.8 series in Cylc UI Server, even though our Conda package is using 2.5.1 (I guess that means it works with our current code base?). It involves reading the changelogs, testing the release with a Cylc complete set up, and upgrading our setuptools dependency.

It would confirm we can go ahead and also release/use `graphene-tornado` in conda forge - https://github.com/conda-forge/graphene-tornado-feedstock/pull/1

**Additional context**

https://pypi.org/project/graphene-tornado/

**Pull requests welcome!**

**Comment by dwsutherland** [comment]
`graphene` v3 (that uses `graphql-core-next`) will be released (soon?), and `graphene-tornado` will release a version then too.. But yes 2.6 first
