### ISSUE TITLE
Fix memory leak

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-uiserver#112]
We've noticed the UIS memory footprint gradually increases.

I just left two workflows running for a day or so, and the Linux kernel eventually killed cylc-uiserver (out of memory).

(The UIS also starts up at over 400MB in size - we should check that that is reasonable).

**Comment by hjoliver** [comment]
There's some evidence to suggest the leak is due to *job* objects in the data store not being culled.

**Comment by dwsutherland** [comment]
Analysis in https://github.com/cylc/cylc-flow/pull/3484 shows this leak is plugged.. The UI Server imports the same delta application mechanism that was fixed.

Closing this issue.
