### ISSUE TITLE
`cylc reload` screws up the UIS?

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-uiserver#119]
**Describe the bug**

- Run a workflow `foo`, observe it in the web UI.
- run `cylc reload foo`
- the UI still recognizes that `foo` is running, but gets no data to display
- stopping and restarting the UIS fixes the problem (so, it appears to be the UIS not the scheduler that is the problem)

**Release version(s) and/or repository branch(es) affected?**

Current master all components

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by dwsutherland** [comment]
Opps! Fix up #120
