### ISSUE TITLE
[question] Make Cylc UI Server a Traitlet application?

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-uiserver#123]
**Describe exactly what you would like to see in an upcoming release**

I had it in my notes from a long time ago, when I first started chopping parts of the JupyterHub single-user application, to get our UI Server working.

One thing that I completely ignored at that time was the whole [Traitlets](https://github.com/ipython/traitlets) code.

Not sure if we need that. In theory the application spawned by the JupyterHub spawners doesn't need to use traitlets, but I never looked if there are any advantages of using it (hence the "question" label).

The only advantages of using it, I **think**, would be a) being able to use Python in the `jupyterhub_config.py` to define variables that could be shared/used in different sections of the file, e.g.

```py
LOG_DATEFMT = '%Y-%m-%dT%H:%M:%S'
c.JupyterHub.log_datefmt = LOG_DATEFMT
c.CylcUIServer.log_datefmt = LOG_DATEFMT
```

and b) using the same tooling as the default application launched by the Hub spawners (i.e. notebook).

But there are probably cons too, like another dependency to the project, we wouldn't have our own configuration file, maybe we want to have more control on how configuration is done, etc.

No strong opinion on this, just remembered about this because yesterday I was reading the JupyterHub code while writing some cookie documentation. 

**Additional context**

Here's one example from Jupyter Core. This is the base class of the `NotebookApp`, which is used by JupyterHub by default with the spawners, and we have replaced with our UI Server.

![image](https://user-images.githubusercontent.com/304786/74869719-5d738e80-53bd-11ea-9374-3134775102f8.png)

It provides the application configuration. The `jupyterhub_config.py` leverages of traitlets to load properties. That's how we have `c.JupyterHub.properties`, `c.ConfigProxy.properties`, and `c.BatchSpawner.properties`, etc.

Traitlets supports things such as defining an object property that will be initialized from the configuration file, with a default value, but that can be overridden by an environment variable.

![image](https://user-images.githubusercontent.com/304786/74870017-dd99f400-53bd-11ea-843f-f75a861f7231.png)

**Pull requests welcome!**

**Comment by oliver-sanders** [comment]
I think this is the right way to go for configuring the hub.

A good trial might be to make the hard-coded scan interval configurable as something like:

```
c.CylcHub.scan_interval = 5  # scan every 5 seconds
```

https://github.com/cylc/cylc-uiserver/blob/831a528a4c05faa1136a125cc7d43138c2fc140a/cylc/uiserver/main.py#L217-L218
