### ISSUE TITLE
GraphQL endpoint must not return data without name/id/status

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-uiserver#128]
**Describe the bug**

From https://github.com/cylc/cylc-ui/issues/390#issuecomment-601499886

At the moment the query

```graphql
subscription {
  workflows {
    id
    name
    status
  }
}
```

returns an empty result (name: "", id: "", etc) for certain workflows, like the "complex" workflow. This complicates the Cylc UI as it needs to filter for empty values.

**Release version(s) and/or repository branch(es) affected?**

`master`
**Steps to reproduce the bug**

1. Run the UI with no workflows
2. Start the complex workflow
3. Keep an eye on the UI and the first time a workflow appears, it will be empty, and the status icon will be showing just an icon with "?"

**Expected behavior**

Data is returned only when it has minimum info like the workflow name, id, status. Jobs, tasks, families are not super important as may be returned as empty arrays IMHO (no nulls if possible).

**Screenshots**

See linked issue.

**Additional context**

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by kinow** [comment]
@dwsutherland do you think this is complicated? If not, maybe I could try to work on this issue.

**Comment by dwsutherland** [comment]
@kinow - I had a play, and it appears GraphQL being feed an empty data element.. I put the following in the resolver:
```
    async def gen(*args: Any, **kwargs: Any) -> AsyncGenerator[Any, None]:
        """
        Args:
            *args: Variable length argument list, varies as per schema.
            **kwargs: Arbitrary keyword arguments, varies as per schema.
        Returns:
            AsyncGenerator[Any, None]: an async generator that will
                yield values from resolvers.
        """
        while True:
            result = await func(*args, **kwargs)
            try:
                if result:
                    if not result[0].id:
                        print(result)
                        print(type(result[0]))
                    else:
                        print(result[0].id)
            except Exception as exc:
                print(f'ERROR: {exc}')
            yield result
            await asyncio.sleep(sleep_seconds)
```
And on the pushes with the blank workflow:
```
[]
<class 'data_messages_pb2.PbWorkflow'>
[]
<class 'data_messages_pb2.PbWorkflow'>
sutherlander|complex
sutherlander|complex
```
This happens because the workflow Subscriber/Publisher is instantiated before the rest of the suite (including data-store creation), and especially evident with the `complex` workflow because it takes a long time to configure/setup... 

The easiest thing to do is nothing lol   ... Because:
- Subscriptions should be event driven not this every 5 seconds thing, and this will change soon..
- And accurately there actually isn't any data at the time the UIServer requests workflow data, and the UI Server corrects itself.
- The null-stripping-backend will strip this (although you're likely to received `null` or `workflow {}`

As this can occur with queries, then two solutions would be:
- Check & reject within the resolver.
- Check & retry in the data sync without populating the UIS  data-store with an empty data container.

The second solution might already be in progress with the UIS GraphQL deltas PR #118

**Comment by kinow** [comment]
Got it @dwsutherland , I think it's fine it the resolvers return data only after the workflow setup is complete. For the UI it will be much easier to handle not having to worry about the missing data, and will display only workflows with name, status, etc.

Once #118 is ready for review will check if this one is fixed too :+1: thanks!

**Comment by kinow** [comment]
Note: I've been running complex workflow this week using Cylc UI, to validate the 0.2 release, but also to test the deltas. And realized I haven't seen this issue lately. It could have been fixed in some previous commit, but I don't know how to confirm this in UIS :+1:

**Comment by kinow** [comment]
Since I had everything opened, why not test it now :-)

I added a `console.log` to the `WorkflowService`. In the browser console in the screenshot below, **that's the very first message received expanded, with the correct data**. I had the Dashboard open, with no workflow.

![image](https://user-images.githubusercontent.com/304786/87493578-2de15d80-c6a1-11ea-862e-b81761eaf3ff.png)

Then I started the workflow, and stopped after three messages were received. All with the correct data apparently.

(p.s.: I had stopped the workflow, but the UI was still displaying it in GScan; that was because I am using Python 3.8, and stopped it with CTRL+C #3685, pressing CTRL+C again the workflow stops and the UI correctly removes it from the GScan)

So happy to close this, but probably better leave to @dwsutherland or somebody else with more experience with UIS to confirm/close :+1:

**Comment by dwsutherland** [comment]
Yeah, go ahead and close it.. It's not relevant now, as the async gen it was using is gone and the subscriptions are delta driven (so the data-store will be available at any point a push is made)... (also args can be used to determine data source)

**Comment by kinow** [comment]
> Yeah, go ahead and close it.. It's not relevant now, as the async gen it was using is gone and the subscriptions are delta driven (so the data-store will be available at any point a push is made)... (also args can be used to determine data source)

Ah! I suspected you would know what change would have fixed it. Thanks @dwsutherland !
