### ISSUE TITLE
websocket connections fail on webkit browsers

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-uiserver#152]
Websockets fail to connect with webkit-based browsers.

It would appear that the cause of this is empty fields in the response header, some reading:

* [SO](https://stackoverflow.com/questions/34679134/websocket-safari-9-invalid-utf-8-sequence-in-header-value)
* [Webkit Bugs](https://bugs.webkit.org/show_bug.cgi?id=139298)
* [Chromium Bugs](https://bugs.chromium.org/p/chromium/issues/detail?id=380075)

Google's fork of WebKit (blink) was patched, however, it would appear that WebKit has not adopted this approach.

Inspecting the response headers in Opera (blink-based) it looks like the `server` field might be missing?

```
access-control-allow-headers: x-requested-with
access-control-allow-methods: POST, GET, OPTIONS
access-control-allow-origin: *
connection: Upgrade
date: Mon, 03 Aug 2020 09:47:38 GMT
sec-websocket-accept: x6JE0chaotdJyvn33cJLLY9iQkc=
sec-websocket-protocol: graphql-ws
server
upgrade: websocket
x-jupyterhub-version: 1.1.0
```

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by kinow** [comment]
>Inspecting the response headers in Opera (blink-based) it looks like the server field might be missing?

Yup, we are removing the Tornado default header.

https://github.com/cylc/cylc-uiserver/blob/252a1a7633eb5d112b11fe956c9ec5425a6fe47c/cylc/uiserver/handlers.py#L37

You could try changing it to another value and see if that works (maybe a space? Or some word that doesn't identify the server)

**Comment by oliver-sanders** [comment]
That was quick! Just tried this diff and Safari is happy again!

```diff
-        self.set_header('Server', '')
+        # self.set_header('Server', '')
```

So whay we are overriding `server` to remove the default `TornadoServer/6.0.4`?

**Comment by kinow** [comment]
>That was quick! Just tried this diff and Safari is happy again!

:tada: 

>So why we are overriding server to remove the default TornadoServer/6.0.4?

To avoid server fingerprinting.
