### ISSUE TITLE
coverage: investigate results

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-uiserver#179]
Coverage results don't match local runs.

See comment https://github.com/cylc/cylc-uiserver/pull/175#issuecomment-793725736

**Comment by kinow** [comment]
Local results:

```bash
----------- coverage: platform linux, python 3.8.3-final-0 -----------
Name                                Stmts   Miss Branch BrPart     Cover
------------------------------------------------------------------------
cylc/uiserver/__init__.py               1      0      0      0   100.00%
cylc/uiserver/config.py                13      0      6      0   100.00%
cylc/uiserver/data_store_mgr.py       159     48     68     10    65.64%
cylc/uiserver/handlers.py              90     19      6      0    73.96%
cylc/uiserver/main.py                  89     24     12      1    69.31%
cylc/uiserver/resolvers.py             90     61     38      1    28.12%
cylc/uiserver/schema.py                60     13     18      1    69.23%
cylc/uiserver/scripts/__init__.py       0      0      0      0   100.00%
cylc/uiserver/scripts/hub.py            5      0      0      0   100.00%
cylc/uiserver/scripts/uis.py            3      0      0      0   100.00%
cylc/uiserver/workflows_mgr.py        143      7     64      6    93.72%
------------------------------------------------------------------------
TOTAL                                 653    172    212     19    69.60%
```

![Screenshot from 2021-03-10 09-43-53](https://user-images.githubusercontent.com/304786/110535927-b7402580-8185-11eb-94ca-3fa224c65c6c.png)

Same branch, on GitHub actions (@MetRonnie `workflow_dispatch` is a life-saver for testing things like this, thanks!).

![Screenshot from 2021-03-10 09-46-34](https://user-images.githubusercontent.com/304786/110535857-a8597300-8185-11eb-8c33-447464aed584.png)

![Screenshot from 2021-03-10 09-44-11](https://user-images.githubusercontent.com/304786/110535943-bc9d7000-8185-11eb-98c1-e31a75f051e0.png)

Looks like Codecov is simply reporting what it has received from GH actions. Maybe the version of `pytest` or `pytest-coverage` is older when running GH actions?

**Comment by kinow** [comment]
Couldn't find documentation confirming the issue with editable mode. Here's the closest I found: https://github.com/pytest-dev/pytest-cov/issues/98#issuecomment-153918021

**Comment by oliver-sanders** [comment]
> Ha! @oliver-sanders reproduced same coverage values from GitHub action locally. Just had to install it in non-editable mode,

Ah, good catch.
