### ISSUE TITLE
authorisation / authentication: cut down on duplicate calls

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-uiserver#207]
See https://github.com/cylc/cylc-uiserver/pull/202#discussion_r614454919

At present some requests may be authenticated &| authorised multiple times (better safe than sorry!).

We should:

* Only perform these calls once per request.
* See if we can provide an authenticate/authorise by default model for greater safety.

**Comment by oliver-sanders** [comment]
@datamel, did https://github.com/cylc/cylc-uiserver/pull/204 close this?

**Comment by datamel** [comment]
I shall double check and get back to you. I think all current processing of auth is necessary for safety. With the caching of the permissions any check is very efficient.

**Comment by oliver-sanders** [comment]
(The comment which started the issue was about me adding auth decorators needlessly to multiple bits of the GraphQL handlers for safety.)

**Comment by datamel** [comment]
Revisiting this, I have checked each handler and the auth decorators are appropriate. In #204, the auth decorators for graphql were replaced by middleware. A [comment](https://github.com/cylc/cylc-uiserver/blob/707386c2933309579e59ae8a6f19efce1f7ac10c/cylc/uiserver/handlers.py#L292) has been left in the code for future reference.
So, closing this issue by #204.
