### ISSUE TITLE
UIS: use jupyter server

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-uiserver#219]
Investigate using the [Jupyter Server](https://jupyter-server.readthedocs.io/en/latest/users/configuration.html) for the UIS.

This may solve a few matters, possibly including:

* https://github.com/cylc/cylc-uiserver/issues/218
* https://github.com/cylc/cylc-uiserver/issues/215

**Pull requests welcome!**

**Comment by dpmatthews** [comment]
Background info: https://blog.jupyter.org/99-ways-to-extend-the-jupyter-ecosystem-11e5dab7c54

**Comment by hjoliver** [comment]
:tada:
