### ISSUE TITLE
Investigate if we can upgrade graphql-ws to 0.4.1

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-uiserver#237]
**Describe exactly what you would like to see in an upcoming release**

It was just released, no idea if it will break our code. It says the 0.4 breaks compatibility for Django, so I guess we should be OK?

https://github.com/graphql-python/graphql-ws/releases/tag/v0.4.0

**Additional context**

**Pull requests welcome!**

**Comment by kinow** [comment]
And now 4.0.1 :sweat_smile: https://github.com/graphql-python/graphql-ws/releases/tag/v0.4.1

**Comment by oliver-sanders** [comment]
Yes we can, we are now on `0.4.4`.

https://github.com/cylc/cylc-uiserver/blob/0692266873e54caf071ce1808778d9743f670cd9/setup.cfg#L56
