### ISSUE TITLE
Project structure

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-uiserver#25]
We are a very flat structure right now. Which works fine so far, but we are exporting two modules right now (`cylc_singleuser`, and `handlers`). If we add more files, we may end up exporting more modules.

And it is dangerous, as in the case we decide to have a file called `job`... that could be exported as `job`, and be mistakenly used when users did a `import job`.

Maybe we should use `cylc_uiserver` as top level package? Then organize our UI Server code within that folder? Me really bad choosing names, so CC'ing @cylc/core :bat:

**Comment by hjoliver** [comment]
Yes we should do that, IMO.

PEP8 on naming conventions:
https://www.python.org/dev/peps/pep-0008/#package-and-module-names

*Modules should have short, all-lowercase names. Underscores can be used in the module name if it improves readability.*

*Python packages should also have short, all-lowercase names, although the use of underscores is discouraged.*

On that basis (underscores discouraged), is `cylcuiserver` OK?

**Comment by kinow** [comment]
>is cylcuiserver OK?

All good for me. Horrible with names, and doesn't affect users/performance/functionality. So +1

One alternative for later, after more thought/discussion, is using `cylc` as a global namespace. Then we could have jinja2filters, cylc, cylc-uiserver, cylc-abc, etc, all sharing the `cylc` top level module namespace: https://setuptools.readthedocs.io/en/latest/setuptools.html#namespace-packages

I think Google... or AWS I think... use that for some of their Python packages. I never used it, so can't comment on pros & cons. For now I'd say `cylcuiserver` it is! :tada: Will leave it here for others to comment too.

Thanks @hjoliver !

**Comment by hjoliver** [comment]
BTW should `cylc_singleuser.py` be renamed to `cylc_uiserver.py`?  or (I guess/) `cylcuiserver.uiserver.py` ... (naming is hard)

**Comment by kinow** [comment]
Haha, good question. That name came from [`jupyterhub.singleuser.py`, ](https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/singleuser.py).

`cylcuiserver.uiserver` sounds a bit redundant, but not sure if there's a better name :worried:

**Comment by matthewrmshin** [comment]
`cylcuiserver.main` or `cylc.uiserver`?

**Comment by kinow** [comment]
`cylc.uiserver` is my favourite. I will have a look over namespaced modules next week, and try a few examples to see if it is simple. If so, we can just use `cylc.` for modules that make sense to share the common namespace :tada:
