### ISSUE TITLE
hub: investigate spawning other users UI servers

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-uiserver#275]
For a multi-user setup, if JupyterHub is run under an account with raised privileges then the Hub can spawn a UIS for the authenticated user.

However, JupyterHub does not allow one user to spawn another user's UIS, largely because Jupyter Server is a single-user application, however, the UIS is a multi-user application and this functionality would be highly desirable for us.

We should investigate whether this limitation can be overcome, start points:

* Existing configurations.
* Admin functionality.
* JupyterHub services (these can stop servers, they should be able to start them too).

See also https://github.com/cylc/cylc-uiserver/issues/171#issuecomment-947321599

**Comment by hjoliver** [comment]
> See also #171 (comment)

Main point from that: you can currently spawn UI Servers on other accounts, but only if you are a **Jupyter admin user**.

**Comment by oliver-sanders** [comment]
Thanks to the new(ish) RABC in JupyterHub this is now a configuration problem.
