### ISSUE TITLE
configuration path root

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-uiserver#291]
Follow on from https://github.com/cylc/cylc-uiserver/issues/189

This project is called cylc-uiserver, however, it configures both the hub and the UIS.

At present the config path is `~/.cylc/hub`, should this be changed to `~/.cylc/uiserver` to match `~/.cylc/flow`?

**Comment by oliver-sanders** [comment]
Agreed, rename to `ui-server`.

**Comment by hjoliver** [comment]
Somewhat relatedly, the server config file can be called:
- `jupyter_config.py`
- `jupyter_cylc_config.py`
- (`jupyterhub_config.py` for hub-launched only)

Should we document/recommend use of `jupyter_cylc_config.py` for maximum clarity?  

Even though `cylc` is in the path name for installed site and user configs, it would makes sense for command line use of temporary config files: `cylc gui --config=jupyter_cylc_config.py`.

**Comment by oliver-sanders** [comment]
> Should we document/recommend use of jupyter_cylc_config.py for maximum clarity?

I think this file targets the Cylc extension so would not be loaded by other Jupyter components. These targeted files should be used to configure the one specific component (server, extension, hub, lab, etc) whereas we use it to configure multiple.

I think using the generic `jupyter_config.py` as documented is the clearest way.
