### ISSUE TITLE
Investigate starting multiple jupyterhub instances (port binding)

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-uiserver#32]
Just occurred to me that when we start Cylc UI Server, we run `jupyterhub`. That's necessary as the Hub is actually the one responsible to spawn the UI Server.

But running `jupyterhub` twice in the same machine results in

```
    Traceback (most recent call last):
      File "/home/kinow/Development/python/workspace/jupyterhub/jupyterhub/app.py", line 2278, in launch_instance_async
        await self.start()
      File "/home/kinow/Development/python/workspace/jupyterhub/jupyterhub/app.py", line 2171, in start
        self.http_server.listen(port, address=ip)
      File "/home/kinow/Development/python/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 143, in listen
        sockets = bind_sockets(port, address=address)
      File "/home/kinow/Development/python/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 168, in bind_sockets
        sock.bind(sockaddr)
    OSError: [Errno 98] Address already in use

```

As the default port is already in use. We can change the Hub's port with `jupyterhub --port 7777`, but it still fails as the proxy uses the 8081 port by default in both.

This issue is to investigate and document how we will initialize the UI Server. I think without having to pass a parameter would be nicer.

**Comment by dwsutherland** [comment]
Doesn't the UI Server start/spawn on user login?

**Comment by dwsutherland** [comment]
It might be handy to start it up whenever. And have the hub discover it.

**Comment by kinow** [comment]
Oh, you are right too @dwsutherland . Momentary brain freeze. @MartinRyan pointed to me that we should have one hub, spawning multiple ui servers.

Sorry the noise. Closing this one :grimacing:

**Comment by dwsutherland** [comment]
@kinow - All good, we all get it.. 

However, does it still have any utility? is the hub able to discover running UI Servers, or do they shutdown if the hub crashes? (i.e. if unable to contact the hub)...

**Comment by kinow** [comment]
Good question. Another question that I just had over dinner. What happens if I connect to a VM with the hub running, but I want to start my own hub?

If that's a valid scenario, then we can at least document here how to do that (which parameters to set up, and where).

And then also check what happens when the hub crashes... good question, will do a quick test later by killing it with SIGKILL and a few different signals.
