### ISSUE TITLE
Task outputs not shown immediately

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-uiserver#341]
Test workflow:
```ini
[scheduling]
    [[graph]]
        R1 = """
           foo:x => bar_x
           foo:y => bar_y
           foo:z => bar_z
        """
[runtime]
    [[foo]]
        script = """
           for OUT in x y z; do
              sleep 5
              cylc message $OUT
           done
        """
        [[[outputs]]]
            x = x
            y = y
            z = z
    [[bar_x, bar_y, bar_z]]
        script = "sleep 10"
```

Using **8.0b3** via conda (:heavy_check_mark:):
![peek1](https://user-images.githubusercontent.com/2362137/160712889-8451438c-6891-437e-a7c8-4da0d641d090.gif)

Using **8.0rc1** or **8.0rc2** via conda (:x:):
![peek2](https://user-images.githubusercontent.com/2362137/160713337-c3d51644-ae73-4e11-a1ce-ceb67d64442e.gif)

**Comment by oliver-sanders** [comment]
@dwsutherland what's left to do after https://github.com/cylc/cylc-flow/pull/4791?
