### ISSUE TITLE
logging: rollover on restart

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-uiserver#352]
Follow on from #349 

The `logging.handlers.RotatingFileHandler` does not support automatically rolling over on restart which would be a nice feature.

To add this, subclass `RotatingFileHandler` and add the logic to call rollover at the end of the `__init__` method, then update the `logging_config` to use this handler instead.

**Pull requests welcome!**

**Comment by datamel** [comment]
Discussed at team meeting in UK. This no longer needs question label as decided sensible to implement.
