### ISSUE TITLE
Add referenced transitive dependencies to setup.cfg

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-uiserver#357]
Do we want to add non-pinned dependencies on pyzmq and graphql-core? (We haven't done this for setup.cfg)

_Originally posted by @MetRonnie in https://github.com/conda-forge/cylc-uiserver-feedstock/issues/32#issuecomment-1134429447_

**Comment by hjoliver** [comment]
What are the pros/cons?

**Comment by oliver-sanders** [comment]
If we directly import something then it should be considered a direct dependency and listed in `setup.cfg`, if it's not directly imported then it should not be in the `setup.cfg`.

If it is a transient dependency which we only make light use of, then we might not want to maintain the version range. In these cases we list the dependency in `setup.cfg` (and on the conda feedstock) but provide no version range (or a loose version range) to allow the direct dependency to control the version range. If we start making heavier usage then we need to start providing appropriate pins.

**Comment by hjoliver** [comment]
Apparently the term is **transitive** (not **transient**) dependency.

https://en.wikipedia.org/wiki/Transitive_dependency
