### ISSUE TITLE
Sometimes, a running workflow displays as stopped

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-uiserver#383]
**Describe the bug**

This is difficult to reproduce. I have noticed it a few times. Possibly it becomes more common if you have a lot of workflows in `~/cylc-run`.

Sometimes, I will click play or play a workflow from the CLI, yet it will remain apparently stopped in the UI. But `cylc scan` shows it is indeed running.

**Additional context**

This may turn out to be a UI Server bug, but the UIServer log shows that `connect_workflow` does happen as it should.

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by oliver-sanders** [comment]
Needs reproducing with latest versions and a reproducible-ish example.

**Comment by oliver-sanders** [comment]
@MetRonnie, possibly closed by #463?

**Comment by MetRonnie** [comment]
Most probably.
