### ISSUE TITLE
subscriptions only yield on change

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-uiserver#384]
> Spotted by @MetRonnie :eyes:

Subscriptions in GraphiQL only come through when the data is updated.

This was the cause behind https://github.com/cylc/cylc-uiserver/issues/328 (which was never really solved).

E.G. Here I run a subscription, but get no results until I install or remove a workflow.

![graphiql](https://user-images.githubusercontent.com/16705946/188147718-ab6fbb55-5fdb-44cc-853e-6099084991f7.gif)

> **Note:** In order to reproduce you must have no running workflows.

> **Note:** Changing the `initialBurst` argument makes no difference.

I think this is a bug, yet strangely if I open the UI, my stopped workflows appear in the workflows list so maybe it's just GraphiQL.

Is this how it's meant to work?

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by hjoliver** [comment]
Any ideas on this one @dwsutherland  ?

**Comment by dwsutherland** [comment]
I'm able to reproduce this.. Will look into it, pretty sure it use to work.

> I think this is a bug, yet strangely if I open the UI, my stopped workflows appear in the workflows list so maybe it's just GraphiQL.

Perhaps because it starts before the first scan is complete (?), so it gets that change

**Comment by dwsutherland** [comment]
The `deltas` entry point does work:
```
subscription {
  deltas (stripNull: true) {
    id
    updated {
      workflow {
        id
        status
        stateTotals
      }
    }
    added {
      workflow{
        id
        status
        stateTotals
      }
    }
  }
}
```
Hence why the UI works .. so it's probably the `workflows` and others

**Comment by dwsutherland** [comment]
Found it.. it's the `ignoreInterval` .. this works:
```
subscription {
  workflows (initialBurst: true, ignoreInterval: 0.0) {
    id
    states
    stateTotals
  }
}
```
Defaults to `2.5` seconds .. reason being; theses entry points dump the entire store (not just the deltas)...

I'll make a change so the first always gets through no matter the interval..

**Comment by dwsutherland** [comment]
fix up.. it's a one liner
