### ISSUE TITLE
Find Available Job Log Files

### ISSUE THREAD

**Issue by datamel** [cylc/cylc-uiserver#398]
For populating the ui with available log files, we can make use of the existing cat-log command... `cylc cat-log -o --mode=l ...`
This will return a list of files from the remote job log directory, helping us provide a drop-down box with files for selection, ensuring we have both custom and standard files.  

The query should be set off in the ui, the graphql query interface needs creating here in the ui-server.

**Comment by oliver-sanders** [comment]
Done with v1.2.0
