### ISSUE TITLE
Add Clean Logic for Info-Files

### ISSUE THREAD

**Issue by datamel** [cylc/cylc-uiserver#416]
Jupyter Server creates two files when starting up the uiserver:
- `jpserver-<pid>-open.html`
- `jpserver-<pid>.json`

These files are currently housed in `~/.local/share/jupyter/runtime` for files generated by `cylc hub` and in `~/.cylc/uiserver/info_files` for files generated by `cylc gui`.

We currently have no cleaning logic in place for these files since jupyter code on clean shutdown will remove these.

Once we have selected a file for reuse, we should add a check that the process is running (and cleaning/reselecting) before pressing ahead with using for opening the gui as it appears these files can get left behind more often than anticipated.

**Comment by dwsutherland** [comment]
This is kind of related to:
https://github.com/cylc/cylc-uiserver/issues/392

**Comment by datamel** [comment]
Update on this, after discussion in UK Team meeting, we should check the selected url is there before opening. It may not be there for two reasons:
- ui-server was opened on another host
- ui-server may no longer be up (e.g. crash, or killed with `kill -9`)

In either case, we can prompt user to clean files and try with another running uiserver until list is exhausted.
This issue should also change the selection of file from random.choice to selecting the newest uiserver file.

**Comment by dwsutherland** [comment]
>  we should check the selected url is there before opening

For `cylc gui` or CLI via UIS? or both?
Do performance implications matter for the latter?

**Comment by datamel** [comment]
> > we should check the selected url is there before opening
> 
> For `cylc gui` or CLI via UIS? or both? Do performance implications matter for the latter?
I think both.

The immediate concern is the `cylc gui` command, since this re-uses the file which could be for an unreachable server - this results in an error page at launch which will prevent the user from seeing the gui. Users may encounter this at present if they have had a server crash, so it is a bug which needs fixing for the next release. At present the solution to this is for them to manually delete the `~/.cylc/uiserver/info_files` folder or to start the gui with `--new` option. 

With regards to the CLI via UIS, I think again this will need cleaning, since rogue files from crashes or `kill -9`s will possibly result in sending of port and host info of servers that are not running?

This is complicated by not knowing the actual host where it was launched. This continues to be a problem of sorts. I did have a look at the Jupyter docs again to see if there was a way to solve this problem but I didn't see anything obvious that could help us here.
