### ISSUE TITLE
immediate disconnect after each connect

### ISSUE THREAD

**Issue by ejhyer** [cylc/cylc-uiserver#435]
EDITED FOR CLARITY AND TERMINOLOGY (CYLC8)

### Description
Running workflows in cylc 8.1.2 using `cylc install --workflow-name=N` to initialize and then `cylc gui` to control. My workflows start normally and then immediately stop after 3-15 seconds, producing a trace in the `cylc gui --debug` log like this:
```
[D 2023-04-01 19:13:43.765 ServerApp] 200 POST /cylc/graphql (127.0.0.1) 1280.48ms
[I 2023-04-01 19:13:47.818 CylcUIServer] [data-store] connect_workflow('~ehyer/NN/run1', <dict>)
[I 2023-04-01 19:13:53.424 CylcUIServer] [data-store] disconnect_workflow('~ehyer/NN/run1')
```

In this example, the workflow was in a running state for 6 seconds before stopping.  Symptoms:
- No user intervention occurred.
- The GUI indicates `Stopped`.
- The GUI STDOUT has a `disconnect workflow` message
- The GUI `Play` button works, but the workflow immediately stops again after 3-15 seconds.

### Reproducible Example
It's pretty clear this is system-specific behavior, and it isn't even all the time-- sometimes it's fine! I'm hoping for some suggestions for how to debug this system-specific behavior.

### Expected Behaviour
Workflows will continue to run until they are stopped by the user.

**Comment by ejhyer** [comment]
OK I'll edit the comment to reflect correct terminology, sorry about that.

**Comment by ejhyer** [comment]
Hi, I apologize for leaving this hanging. I have some new indicators from the case where my workflow changes to "stopped/disconnected" without my doing anything. Here is the log from `cylc gui`: 
`[I 2023-05-25 16:01:30.756 CylcUIServer] $ cylc play --color=never --mode live RA_NVG45R/run1
[I 2023-05-25 16:01:33.600 CylcUIServer] [data-store] connect_workflow('~ehyer/RA_NVG45R/run1', <dict>)
[I 2023-05-25 16:01:43.611 CylcUIServer] [data-store] disconnect_workflow('~ehyer/RA_NVG45R/run1')
[I 2023-05-25 16:01:50.207 CylcUIServer] $ cylc cat-log --mode=tail --force-remote --prepend-path ~ehyer/RA_NVG45R/run1 -f scheduler/03-restart-03.log
`
And here is the trace from the workflow log:
`2023-05-25T16:01:39Z INFO - [20221201T0000Z/stage_initial_concentrations waiting job:01 flows:1] => preparing
2023-05-25T16:01:40Z INFO - [20221201T0000Z/stage_initial_concentrations preparing job:01 flows:1] submitted to localhost:background[225364]
2023-05-25T16:01:40Z INFO - [20221201T0000Z/stage_initial_concentrations preparing job:01 flows:1] => submitted
2023-05-25T16:01:40Z INFO - [20221201T0000Z/stage_initial_concentrations submitted job:01 flows:1] health: submission timeout=None, polling intervals=PT15M,...`
And when I run 'cylc scan' the suite does not show up.
I am able to get the suite moving again by pressing play in the GUI, which results in this trace from `cylc gui`:
`[I 2023-05-25 16:07:15.196 CylcUIServer] $ cylc play --color=never --mode live RA_NVG45R/run1
[I 2023-05-25 16:07:19.135 CylcUIServer] [data-store] connect_workflow('~ehyer/RA_NVG45R/run1', <dict>)
[I 2023-05-25 16:07:28.805 CylcUIServer] [data-store] disconnect_workflow('~ehyer/RA_NVG45R/run1')`
This additional trace appears in the workflow log:
`2023-05-25T16:07:19Z INFO - [20221201T0000Z/forecast_ready_to_start waiting job:01 flows:1] => preparing
2023-05-25T16:07:20Z INFO - [20221201T0000Z/forecast_ready_to_start preparing job:01 flows:1] submitted to localhost:background[251951]
2023-05-25T16:07:20Z INFO - [20221201T0000Z/forecast_ready_to_start preparing job:01 flows:1] => submitted
2023-05-25T16:07:20Z INFO - [20221201T0000Z/forecast_ready_to_start submitted job:01 flows:1] health: submission timeout=None, polling intervals=PT15M,...`

**Comment by ejhyer** [comment]
It seems to me that the sequence is 
1) gui/connect_workflow 
2) after 0-5s delay, activity in workflow log: preparing/submitted/submitted/health
3) workflow log activity completes within 2s
4) 3-10s after workflow_log/heath, gui/disconnect_workflow

**Comment by MetRonnie** [comment]
If you are not getting any obvious errors in your workflow scheduler log then I suggest you open a discussion at https://cylc.discourse.group/ and post your `flow.cylc` or `suite.rc` and your full `scheduler/log` so that we can help you debug the problem.

**Comment by ejhyer** [comment]
Thanks, I was ignorant of that option. I'll do that! OK to close this (again).
