### ISSUE TITLE
Create "cylc show" GUI equivalent to share job prerequisite stat

### ISSUE THREAD

**Issue by jarich** [cylc/cylc-uiserver#492]
### Problem

With Cylc 7, we use task meta data and the "cylc show" GUI window to provide URLs to the documentation of failing tasks. For some workflows, all tasks point to the same trouble-shooting documentation, and for most of the others, tasks each point to task-specific documentation. In all cases, when a task fails, our support staff know to bring up the "cylc show" GUI window, and copy and paste the URL from there.

![image](https://github.com/cylc/cylc-uiserver/assets/13433/a61db260-18f1-4919-9bc2-3c0a1432db74)

I can seet that "cylc show"  works on the command line for Cylc 8:

```
[user@host ~]$ cylc show basic-workflow/run6//8/a
title: (not given)
importance: 1
description: Do a thing for %(task)s
URL: https://code.site.com/basic-workflow/run6/docs/a
state: succeeded
prerequisites: (n/a for past tasks)
outputs: ('-': not completed)
  - 8/a expired
  + 8/a submitted
  - 8/a submit-failed
  + 8/a started
  + 8/a succeeded
  - 8/a failed
```

but I might not be correctly identifying how to achieve the same via the UI Server.

![image](https://github.com/cylc/cylc-uiserver/assets/13433/554aa2d5-c760-4508-b834-01009478a214)

### Proposed Solution

Add a "cylc show" view to the UI Server, ideally where `flow.cylc[meta]workflow_URL` and `[runtime][<namespace>][meta]URL` are links we can click on to open in a new window.

**Comment by hjoliver** [comment]
It's in the works, just not done yet: https://github.com/cylc/cylc-ui/issues/1071

**Comment by hjoliver** [comment]
@jarich - can you take a look at the referenced UI issue and close this one if you're happy with it?

**Comment by jarich** [comment]
Thanks. I did check all the issues in cylc-uiserver, but missed checking in cylc-iu. That will do nicely, thanks.
