### ISSUE TITLE
Add right-click context menu?

### ISSUE THREAD

**Issue by ColemanTom** [cylc/cylc-uiserver#549]
Froce of habit makes me right-click on tasks to access the context menu.
It feels more natural to right-click on something to open a menu than left click as that is how it works in almost every application.
Could a right-click context menu be added, with the same outcomes as the left-click?

**Comment by hjoliver** [comment]
> It feels more natural to right-click on something to open a menu than left click as that is how it works in almost every application.

I think that's a desktop GUI-centric perspective, not true for web applications which have to distinguish between the browser context and the web app running in the browser.

E.g. in the GitHub web UI, like Cylc UI, left-clicking on the upper left "burger" button (say) brings up the web-application (GitHub) menu, but right-clicking brings up the browser menu.

**Comment by ColemanTom** [comment]
That depends on the application. We have been socially trained to associate the burger icon as a menu and to left click on it. For the Cylc UI, they are circles and text (noting you cannot do anything to the text which is a separate bugbear of mine, reminding me of labels next to buttons in a form which make you click the small button rather than the text).

But I take your point that it is yes, a desktop centric view and many consider overriding right-click context menu as bad practice (although I have seen it done very well, but they are for very specific applications with a very targetted audience).
