### ISSUE TITLE
Show xtriggers as nodes in the graph view?

### ISSUE THREAD

**Issue by ColemanTom** [cylc/cylc-uiserver#553]
### Problem

When I view the graph view, I cannot see `xtriggers` on the display. I haven't been able to figure out how to turn them on, so either it's not obvious and that could be improved, or it can't be done?

### Proposed Solution

Add an option to show/hide xtriggers on the graph, or make it more visible if it is there.

**Comment by hjoliver** [comment]
👍 - we already plan to do this, just haven't had a chance to implement it yet.

**Comment by hjoliver** [comment]
See:
- https://github.com/cylc/cylc-ui/issues/131
- https://github.com/cylc/cylc-ui/issues/331
-

**Comment by ColemanTom** [comment]
Oh, I didn't realise there was a UI and a UIServer - this was completely the wrong spot for this anyway isn't it? Should https://github.com/cylc/cylc-uiserver/issues/552 be moved to the `cylc-ui` one ?

**Comment by hjoliver** [comment]
No worries @ColemanTom, it's trivial for us to transfer issues between repos, plus cross-references show up between them.
