### ISSUE TITLE
cylc show for tasks?

### ISSUE THREAD

**Issue by ColemanTom** [cylc/cylc-uiserver#554]
### Problem

Through the UI I can't see a way to show current status of task prereqs (including xtriggers). I recognise there is the graph, but, some like text, and also, [I can't see how to show xtriggers on the graph](https://github.com/cylc/cylc-uiserver/issues/553).

### Proposed Solution

Could we please have the ability to do `cylc show` on tasks (not jobs)?

**Comment by hjoliver** [comment]
👍 - this is planned - see https://github.com/cylc/cylc-ui/issues/1071 - we just have to wait for it to rise up the priority list
