### ISSUE TITLE
Revisit jupyterhub_config location for Cylc UI

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-uiserver#80]
Developers may have different directory structures for their projects. Some checking out the code in a common directory like `~/code/`, others using different parent directories (e.g. `~/javascript/`, `~/python/`), or even using multiple git working trees.

Cylc UI Server has a `jupyterhub_config.py` file used for development. That file needs a location of the static files, produced by Cylc UI. And at the moment it is expecting the developer to have both projects sharing a root directory.

We need to find another solution that accommodates these possible developer environment configurations.

**Comment by kinow** [comment]
@oliver-sanders can we close this one after #173?

**Comment by oliver-sanders** [comment]
Oh yes.
